locales:
  en:
    name: Lule Sami Keyboards
    description: Keyboards for the Lule Sami language from the Divvun group at UiT.
  nb:
    name: Lulesamiske tastatur
    description: Tastatur for lulesamisk fra Divvun-gruppa.
  sv:
    name: Lulesamiska tangentbord
    description: Tangentbord för lulesamiska från Divvun-gruppen vid UiT.
author: 'The Divvun Group, UiT Norgga árktalaš universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga árktalaš universitehta
